import os
import sys

# Ensure root directory is in python path
current_dir = os.path.dirname(os.path.abspath(__file__))
parent_dir = os.path.dirname(current_dir)
if parent_dir not in sys.path:
    sys.path.append(parent_dir)

from database.db import connect
from policy_engine.enforcer import check_policy

def generate_audit_report(image_name):
    """
    Generates a professionally formatted text-based Executive Audit Report
    from the raw database metrics and Policy Engine decisions.
    """
    conn = connect()
    cursor = conn.cursor()
    
    cursor.execute("""
        SELECT i.pulls, i.last_updated, s.critical, s.high, s.medium, s.low, s.secrets, s.risk_score, s.risk_level
        FROM images i
        JOIN scan_results s ON i.id = s.image_id
        WHERE i.name = ?
        ORDER BY s.rowid DESC LIMIT 1
    """, (image_name,))
    
    row = cursor.fetchone()
    conn.close()
    
    if not row:
        return f"No audit data found for {image_name}."

    pulls, updated, crit, high, med, low, secrets, score, level = row
    
    action, reason = check_policy(image_name)
    
    report = f"""
===================================================
     DR.DOCKER - EXECUTIVE AUDIT REPORT
===================================================

TARGET IMAGE: {image_name}
LAST SCANNED/UPDATED: {updated}
DOCKER HUB PULLS: {pulls}

--- POLICY DECISION ENGINE -----------------------
ENFORCEMENT ACTION: {action}
REASONING: {reason}

--- VULNERABILITY BREAKDOWN ----------------------
CRITICAL CVEs: {crit} 
HIGH CVEs:     {high}
MEDIUM CVEs:   {med}
LOW CVEs:      {low}
EXPOSED SECRETS / API KEYS: {secrets}

--- RISK METRICS ---------------------------------
CALCULATED RISK SCORE: {score} / 100
ASSIGNED RISK LEVEL:   {level}

===================================================
GENERATED BY DR. DOCKER FORENSICS ENGINE
===================================================
"""
    return report
